[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.20"
reqwasm = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
log = "0.4"